try pinning postgres to 17.4-bookwarm

diff --git a/.github/workflows/check_smoke_tests.yml b/.github/workflows/check_smoke_tests.yml
--- a/.github/workflows/check_smoke_tests.yml
+++ b/.github/workflows/check_smoke_tests.yml
@@ -12,13 +12,13 @@ jobs:
 
     strategy:
       matrix:
-        database: [postgres]  # Matrix for database types
-        # database: [postgres, sqlite, mysql, sqlserver]  # Matrix for database types
+        # database: [postgres]  # Matrix for database types
+        database: [postgres, sqlite, mysql, sqlserver]  # Matrix for database types
 
     services:
       postgres:
-        # image: postgres:17
-        image: ghcr.io/cdcgov/recordlinker/postgres:17
+        image: postgres:17.4-bookwarm
+        # image: ghcr.io/cdcgov/recordlinker/postgres:17
         # image: ${{ matrix.database == 'postgres' && 'ghcr.io/cdcgov/recordlinker/postgres:17' || 'postgres:17' }}
 
         ports:
@@ -27,7 +27,7 @@ jobs:
           POSTGRES_PASSWORD: pw
           # POSTGRES_DB: postgres
           # POSTGRES_USER: postgres
-          # DB_URI: "postgresql+psycopg2://postgres:pw@postgres:5432/postgres"
+          # DB_URI: "postgresql+psycopg2://postgres:pw@localhost:5432/postgres"
 
       mysql:
         image: mysql:8
@@ -70,24 +70,24 @@ jobs:
         docker tag rl-service-image ghcr.io/${{ env.PACKAGE_NAME }}/rl-service:latest
         docker push ghcr.io/${{ env.PACKAGE_NAME }}/rl-service:latest
 
-    - name: Check if cached postges:17 image exists in GitHub Container Registry
-      id: check_postgres_image
-      run: |
-          docker pull ghcr.io/${{ env.PACKAGE_NAME }}/postgres:17 || echo "No cached image found"
+    # - name: Check if cached postges:17 image exists in GitHub Container Registry
+    #   id: check_postgres_image
+    #   run: |
+    #       docker pull ghcr.io/${{ env.PACKAGE_NAME }}/postgres:17 || echo "No cached image found"
 
-    - name: Build and push postgres:17 Docker image if not cached
-      if: steps.check_postgres_image.outcome == 'failure'
-      run: |
-        # Build the Docker image, tag it, & push to ghcr
-        echo "Building and pushing postgres:17 Docker image..."
-        docker pull postgres:17
-        docker tag postgres:17 ghcr.io/${{ env.PACKAGE_NAME }}/postgres:17
-        docker push ghcr.io/${{ env.PACKAGE_NAME }}/postgres:17
+    # - name: Build and push postgres:17 Docker image if not cached
+    #   if: steps.check_postgres_image.outcome == 'failure'
+    #   run: |
+    #     # Build the Docker image, tag it, & push to ghcr
+    #     echo "Building and pushing postgres:17 Docker image..."
+    #     docker pull postgres:17
+    #     docker tag postgres:17 ghcr.io/${{ env.PACKAGE_NAME }}/postgres:17
+    #     docker push ghcr.io/${{ env.PACKAGE_NAME }}/postgres:17
 
-    - name: Skip building and pushing postgres:17 Docker image if cached
-      if: steps.check_postgres_image.outcome == 'success'
-      run: |
-        echo "No need to build and push postgres:17 Docker image, using cached image..."
+    # - name: Skip building and pushing postgres:17 Docker image if cached
+    #   if: steps.check_postgres_image.outcome == 'success'
+    #   run: |
+    #     echo "No need to build and push postgres:17 Docker image, using cached image..."
 
     - name: Check out repository
       uses: actions/checkout@v4
