revert rl to ghcr push/pull

diff --git a/.github/workflows/check_smoke_tests.yml b/.github/workflows/check_smoke_tests.yml
--- a/.github/workflows/check_smoke_tests.yml
+++ b/.github/workflows/check_smoke_tests.yml
@@ -7,21 +7,21 @@ on:
     branches: [main]
 
 jobs:
-  build-rl-with-docker:
-    runs-on: ubuntu-latest
+  # build-rl-with-docker:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v4
-      - uses: docker/setup-buildx-action@v2
-      - uses: docker/build-push-action@v5
-        with:
-          context: .
-          cache-from: type=gha
-          cache-to: type=gha, mode=max
-          push: false
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: docker/setup-buildx-action@v2
+  #     - uses: docker/build-push-action@v5
+  #       with:
+  #         context: .
+  #         cache-from: type=gha
+  #         cache-to: type=gha, mode=max
+  #         push: false
 
   smoke_tests:
-    needs: build-rl-with-docker
+    # needs: build-rl-with-docker
     runs-on: ubuntu-latest
 
     strategy:
@@ -55,9 +55,24 @@ jobs:
       - name: Check out repository
         uses: actions/checkout@v4
 
-      - name: Build RL image from GitHub Actions cache
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build and push RecordLinker image to GHCR if necessary
+        env:
+          PR_NUMBER: ${{ github.event.number }}
         run: |
-          docker buildx build --cache-from=type=gha --load -t rl-service .
+          if ! docker pull ghcr.io/${{ env.REPO }}/rl-service:pr-$PR_NUMBER; then
+            echo "RecordLinker image not found, building and pushing to GHCR"
+            docker build -t ghcr.io/${{ env.REPO }}/rl-service:pr-$PR_NUMBER .
+            docker push ghcr.io/${{ env.REPO }}/rl-service:pr-$PR_NUMBER
+          else
+            echo "RecordLinker image found, using cached image."
+          fi
 
       - name: Start RecordLinker Service and Run Smoke Tests
         env:
@@ -77,7 +92,7 @@ jobs:
           docker run -d --name rl-service \
             --network="host" \
             -e DB_URI=$DB_URI \
-            rl-service # use image cached from GitHub Actions
+            ghcr.io/${{ env.REPO }}/rl-service:pr-$PR_NUMBER  # Use the cached image
 
 
           # Wait for the RL Service to be healthy
